title = "Focuser160MQ"

[General]
name = 'LNA Focus160'
version = '0.1.0'
description = 'Interface for Perkin-Elmer Focuser'
startup = true

[Device]
deviceType = 'Focuser'
deviceID = '3285e9af-8d1d-4f9d-b368-d129d8e9a24b' # https://guidgenerator.com/online-guid-generator.aspx
absolute = true
max_step = 50000
maxincrement = 0
stepsize = 0
tempcompavailable = false
temp_comp = false
device_ip = '192.168.1.250'
device_port = 5001

[Network]
ip_address = '192.168.50.190'
port_pub = 7001
port_pull = 7002
port_rep = 7003

[Database]
db_name = 'db_name'
db_user = 'username'
db_password = 'password'

[Logging]
log_level = 'INFO'
log_to_stdout = false
log_max_size_mb = 5
log_num_keep = 10
